package Productos.Variantes;

import Principales.FiltrosTextField;
import Principales.VerTabla;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Franco
 */
public class Variantes extends javax.swing.JInternalFrame {
    Boolean nuevo = false;
    VerTabla v = new VerTabla();
    TablasVariantes v2 = new TablasVariantes();
    
    JPanel pUnidad1;
    JPanel pBebida1;
    JScrollPane sUnidad1;
    JScrollPane sBebida1;
    JTable tabla;
    JTextField txtTotal;
    ConexionVariantes conn = new ConexionVariantes();
    Boolean eligio = false;
    FiltrosTextField filtros = new FiltrosTextField();
    public Variantes(JTable table, JTextField txtTot, JPanel punidad, JPanel pbebida, JScrollPane sunidad, JScrollPane sbebida) {
        initComponents();
        txtTotal = txtTot;
        tabla = table;
        pUnidad1 = punidad;
        pBebida1 = pbebida;
        sUnidad1 = sunidad;
        sBebida1 = sbebida;
        

        filtros.filtrotamaño(txtNombre, 29);
          
        
        v2.visualizar_variantes(tablap, "", 0);
        tablap.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
                // print first column value from selected row
                txtIdProducto.setText(tablap.getValueAt(tablap.getSelectedRow(), 0).toString());
                txtNombre.setText(tablap.getValueAt(tablap.getSelectedRow(), 1).toString());
                String tipo = tablap.getValueAt(tablap.getSelectedRow(), 2).toString();
                
                
                btnEliminar.setEnabled(true);
                
                Integer inde = 0;
                if(tipo == "Ensalada"){
                    inde = 0;
                }else if(tipo == "Salsa"){
                    inde = 1;
                }
                
                cmbTipo.setSelectedIndex(inde);
            
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablap = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();

        setClosable(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_document-new_9241.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_edit-trash_9263.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_no_9424.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_floppy_disk_save_103863.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tablap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tipo:");

        cmbTipo.setEditable(true);
        cmbTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensalada", "Salsa" }));
        cmbTipo.setEnabled(false);
        cmbTipo.setFocusable(false);
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Codigo:");

        txtIdProducto.setEditable(false);
        txtIdProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //Habilita los campos
        txtNombre.setEditable(true);
        cmbTipo.setEditable(true);
        cmbTipo.setEnabled(true);
        tablap.setEnabled(false);
        
        //Habilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        //Limpiar los datos
        txtIdProducto.setText("");
        txtNombre.setText("");
        
        //Activamos el flag nuevo
        nuevo = true;
        
        //Damos foco al campo nombre
        txtNombre.requestFocusInWindow();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int rta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar el producto?");
        if(rta != 0) {
            return;
        }else{
            Integer ide = Integer.parseInt(txtIdProducto.getText());

            conn.eliminar(ide, "variantes");
            
            txtIdProducto.setText("");
            txtNombre.setText("");

            v2.visualizar_variantes(tablap, "", 0);
            tablap.setEnabled(true);
            
            btnEliminar.setEnabled(false);
            tablap.repaint();
            
        pUnidad1.removeAll();  
        pBebida1.removeAll();

        ResultSet rs = conn.select("variantes");
        
        Integer tEnsaladas = 0;
        Integer tSalsas = 0;

        
        try{
            while(rs.next()){
                Integer id = rs.getInt(1);
                String nombre = rs.getString(2);
                Integer tipo = rs.getInt(3);

                JButton por = new JButton();
                por.addActionListener(new ActionListener(){
                    public void actionPerformed(ActionEvent ae) {
                        conn.guardarconsumoventa(nombre, 0, 1, 2);
                        v.visualizar_tablaventa(tabla, txtTotal);
                    }
                });

                //Cargo el icono en un label para luego guardarlo en el button

                JLabel nomprodu = new JLabel(nombre);
                JLabel precprodu = new JLabel();


                por.setLayout(new BorderLayout());
                por.add(nomprodu, BorderLayout.CENTER);
                por.add(precprodu, BorderLayout.EAST);

                por.setSize(180,60);
                por.setVisible(true);

                if(tipo == 0){
                    por.setLocation(1,tEnsaladas);
                    pUnidad1.add(por);
                    tEnsaladas = tEnsaladas + 65;
                    pUnidad1.setPreferredSize(new Dimension(180,tEnsaladas));
                }
                if(tipo == 1){
                    por.setLocation(1,tSalsas);
                    pBebida1.add(por);
                    tSalsas = tSalsas + 65;
                    pBebida1.setPreferredSize(new Dimension(180,tSalsas));
                }
            }

            } catch (Exception ex) {
                System.out.println("Error en cargar productos principal");
            }


            sUnidad1.setViewportView(pUnidad1);
            sUnidad1.getViewport().setView(pUnidad1);
            pUnidad1.setLayout(null);


            sBebida1.setViewportView(pBebida1);
            sBebida1.getViewport().setView(pBebida1);
            pBebida1.setLayout(null);

            
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Validaciones        
        if(txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe escribir un nombre de producto");
            txtNombre.requestFocusInWindow();
            return;
        }
        
                
        String nombre1 = txtNombre.getText();
        Integer tipo1 = cmbTipo.getSelectedIndex();

        
        if(nuevo == true){
            conn.guardarvariante(nombre1, tipo1);
        }
        
        //Deshabilita los campos
        txtNombre.setEditable(false);
        cmbTipo.setEnabled(false);
        
        //Deshabilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        txtIdProducto.setText("");
        txtNombre.setText("");
        
        v2.visualizar_variantes(tablap, "", 0);
        tablap.setEnabled(true);
        tablap.repaint();
        
        pUnidad1.removeAll();  
        pBebida1.removeAll();

        ResultSet rs = conn.select("variantes");
        
        Integer tUnidad = 0;
        Integer tBebida = 0;

        
        try{
            while(rs.next()){
                Integer id = rs.getInt(1);
                String nombre = rs.getString(2);
                Integer tipo = rs.getInt(3);

                JButton por = new JButton();
                por.addActionListener(new ActionListener(){
                    public void actionPerformed(ActionEvent ae) {
                        conn.guardarconsumoventa(nombre, 0,1,2);
                        v.visualizar_tablaventa(tabla, txtTotal);
                    }
                });

                //Cargo el icono en un label para luego guardarlo en el button

                JLabel nomprodu = new JLabel(nombre);

                nomprodu.setFont(new Font("Serif", Font.BOLD, 14));

                por.setLayout(new BorderLayout());
                por.add(nomprodu, BorderLayout.CENTER);

                por.setSize(150,40);
                por.setVisible(true);

                if(tipo == 0){
                    por.setLocation(1,tUnidad);
                    pUnidad1.add(por);
                    tUnidad = tUnidad + 42;
                    pUnidad1.setPreferredSize(new Dimension(0,tUnidad));
                }
                if(tipo == 1){
                    por.setLocation(1,tBebida);
                    pBebida1.add(por);
                    tBebida = tBebida + 42;
                    pUnidad1.setPreferredSize(new Dimension(0,tBebida));
                }
                }


            }catch(Exception ex){
                System.out.println("Error en cargar productos principal");
            }
        
        
        
        sUnidad1.setViewportView(pUnidad1);
        sUnidad1.getViewport().setView(pUnidad1);
        pUnidad1.setLayout(null);
        
        
        sBebida1.setViewportView(pBebida1);
        sBebida1.getViewport().setView(pBebida1);
        pBebida1.setLayout(null);
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Deshabilita los campos
        txtNombre.setEditable(false);
        cmbTipo.setEnabled(false);
        
        //Deshabilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        txtIdProducto.setText("");
        txtNombre.setText("");
        
        
        tablap.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed

    }//GEN-LAST:event_cmbTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablap;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
