package Productos.Combos;

import Principales.FiltrosTextField;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Franco
 */
public class Combos extends javax.swing.JInternalFrame {
    
    
    public class product {

        private String nombre;
        private String id;

        public product(String nombre, String id) {
            this.nombre = nombre;
            this.id = id;
        }

        public String getID() {
            return id;
        }

        public String toString() {
            return nombre;
        }
    }
    Boolean nuevo = false;
    TablasCombos v = new TablasCombos();
    String idunitario;
    JPanel pCombo;
    JScrollPane sCombo;
    JTable tabla;
    JTextField txtTotal;
    ConexionCombos conn = new ConexionCombos();
    Boolean eligio = false;
    FiltrosTextField filtros = new FiltrosTextField();
    public Combos(JTable table, JTextField txtTot, JPanel pcombo1, JScrollPane scombo1) {
        initComponents();
        txtTotal = txtTot;
        tabla = table;
        pCombo = pcombo1;
        sCombo = scombo1;
        
        filtros.filtroeneteros(txtPrecio);
        filtros.filtrotamaño(txtPrecio, 5);
        filtros.filtroeneteros(txtPrecioPedidosya);
        filtros.filtrotamaño(txtPrecioPedidosya, 5);
        filtros.filtrotamaño(txtNombre, 29);
        
        Connection con = conn.conectar();
        ResultSet rs1 = null;
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM productos");
            rs1 = ps.executeQuery();
            DefaultComboBoxModel value = new DefaultComboBoxModel();
            cmbProductos.setModel(value);
            while(rs1.next()){
                value.addElement(new product(rs1.getString(2),rs1.getString(1)));
            }
        } catch (Exception ex) {
            System.out.println("Error de consulta");
        }
         
        
        v.visualizar_combos(tablap);
        v.visualizar_comboproducto(tProductos, 0);
        tablap.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
                // print first column value from selected row
                txtIdProducto.setText(tablap.getValueAt(tablap.getSelectedRow(), 0).toString());
                txtNombre.setText(tablap.getValueAt(tablap.getSelectedRow(), 1).toString());
                Integer id = Integer.parseInt(txtIdProducto.getText());
                txtPrecio.setText(tablap.getValueAt(tablap.getSelectedRow(), 2).toString());
                txtPrecioPedidosya.setText(tablap.getValueAt(tablap.getSelectedRow(), 3).toString());
                
                v.visualizar_comboproducto(tProductos, id);
                btnEditar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnAgregar.setEnabled(true);
                
            
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablap = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioPedidosya = new javax.swing.JTextField();
        cmbProductos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();

        setClosable(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_document-new_9241.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_kate_8739.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_edit-trash_9263.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_no_9424.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_floppy_disk_save_103863.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tablap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Codigo:");

        txtIdProducto.setEditable(false);
        txtIdProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PedidosYa:");

        txtPrecioPedidosya.setEditable(false);
        txtPrecioPedidosya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrecioPedidosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioPedidosyaActionPerformed(evt);
            }
        });

        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Contiene:");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrecio))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecioPedidosya, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecioPedidosya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //Habilita los campos
        txtNombre.setEditable(true);
        txtPrecio.setEditable(true);
        txtPrecioPedidosya.setEditable(true);
        tablap.setEnabled(false);
        
        //Habilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        //Limpiar los datos
        txtIdProducto.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtPrecioPedidosya.setText("");
        
        //Activamos el flag nuevo
        nuevo = true;
        btnAgregar.setEnabled(false);
        
        //Damos foco al campo nombre
        txtNombre.requestFocusInWindow();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //Habilita los campos
        txtPrecio.setEditable(true);
        txtPrecioPedidosya.setEditable(true);
        tablap.setEnabled(false);
        
        //Habilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        //Desactivamos el flag nuevo
        eligio = false;
        nuevo = false;
        btnAgregar.setEnabled(false);
        
        //Damos foco al campo nombre
        txtPrecio.requestFocusInWindow();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int rta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar el producto?");
        if(rta != 0) {
            return;
        }else{
            Integer ide = Integer.parseInt(txtIdProducto.getText());

            conn.eliminar(ide, "combos");
            
            txtIdProducto.setText("");
            txtNombre.setText("");
            txtPrecio.setText("");
            txtPrecioPedidosya.setText("");
            btnAgregar.setEnabled(false);
            v.visualizar_combos(tablap);
            tablap.setEnabled(true);
            
            btnEditar.setEnabled(false);
            btnEliminar.setEnabled(false);
            tablap.repaint();
            
        pCombo.removeAll();  

        ResultSet rs = conn.select("combos");
        
        Integer tCombo = 0;

        
        try{
            while(rs.next()){
                Integer id = rs.getInt(1);
                String nombre = rs.getString(2);
                Integer precio = rs.getInt(3);


                JButton por = new JButton();
                por.addActionListener(new ActionListener(){
                    public void actionPerformed(ActionEvent ae) {
                        conn.guardarconsumoventa(nombre, precio,1,1);
                        
                        
                        Connection con = conn.conectar();
                        ResultSet rs3 = null;
                        try {
                            PreparedStatement ps3 = con.prepareStatement("SELECT * FROM comboproducto c RIGHT JOIN  productos p ON c.id_producto = p.id WHERE c.id_combo = "+id);
                            rs3 = ps3.executeQuery();
                            while(rs3.next()){
                                conn.guardarconsumoventa(rs3.getString(5), 0, rs3.getInt(3),0);
                            }
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                        v.visualizar_tablaventa(tabla, txtTotal);
                    }
                });

                //Cargo el icono en un label para luego guardarlo en el button

                JLabel nomprodu = new JLabel(nombre);
                JLabel precprodu = new JLabel();

                precprodu = new JLabel("$"+precio);
                nomprodu.setFont(new Font("Serif", Font.BOLD, 18));
                precprodu.setFont(new Font("Serif", Font.BOLD, 18));

                por.setLayout(new BorderLayout());
                por.add(nomprodu, BorderLayout.CENTER);
                por.add(precprodu, BorderLayout.EAST);

                por.setSize(180,60);
                por.setVisible(true);

                    por.setLocation(1,tCombo);
                    pCombo.add(por);
                    tCombo = tCombo + 65;
                    pCombo.setPreferredSize(new Dimension(180,tCombo));

            }

            } catch (Exception ex) {
                System.out.println("Error en cargar productos principal");
            }


            sCombo.setViewportView(pCombo);
            sCombo.getViewport().setView(pCombo);
            pCombo.setLayout(null);


            
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Validaciones        
        if(txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe escribir un nombre de producto");
            txtNombre.requestFocusInWindow();
            return;
        }
        
        if(txtPrecio.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe escribir un precio");
            txtPrecio.requestFocusInWindow();
            return;
        }
        
                
        String nombre1 = txtNombre.getText();
        Integer precio1 = Integer.parseInt(txtPrecio.getText());
        Integer precio2 = 0;
        if(!txtPrecioPedidosya.getText().equals("")) {
            precio2 = Integer.parseInt(txtPrecioPedidosya.getText());
        }
        
        if(nuevo == true){
            conn.guardarcombo(nombre1, precio1, precio2);
        }
        else{
            Integer id = Integer.parseInt(txtIdProducto.getText());
            conn.editarcombo(id, precio1, precio2); 
        }
        
        //Deshabilita los campos
        txtNombre.setEditable(false);
        txtPrecio.setEditable(false);
        txtPrecioPedidosya.setEditable(false);
        
        //Deshabilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAgregar.setEnabled(false);
        txtIdProducto.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtPrecioPedidosya.setText("");
        
        v.visualizar_combos(tablap);
        tablap.setEnabled(true);
        tablap.repaint();
        
        pCombo.removeAll();  

        ResultSet rs = conn.select("combos");
        
        Integer tCombo = 0;

        
        try{
            while(rs.next()){
                Integer id = rs.getInt(1);
                String nombre = rs.getString(2);
                Integer precio = rs.getInt(3);

                JButton por = new JButton();
                por.addActionListener(new ActionListener(){
                    public void actionPerformed(ActionEvent ae) {
                        conn.guardarconsumoventa(nombre, precio,1,1);
                        
                        Connection con = conn.conectar();
                        ResultSet rs3 = null;
                        try {
                            PreparedStatement ps3 = con.prepareStatement("SELECT * FROM comboproducto c RIGHT JOIN  productos p ON c.id_producto = p.id WHERE c.id_combo = "+id);
                            rs3 = ps3.executeQuery();
                            while(rs3.next()){
                                conn.guardarconsumoventa(rs3.getString(5), 0, rs3.getInt(3),0);
                            }
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                        v.visualizar_tablaventa(tabla, txtTotal);
                    }
                });

                //Cargo el icono en un label para luego guardarlo en el button

                JLabel nomprodu = new JLabel(nombre);
                JLabel precprodu = new JLabel();

                precprodu = new JLabel("$"+precio);
                nomprodu.setFont(new Font("Serif", Font.BOLD, 18));
                precprodu.setFont(new Font("Serif", Font.BOLD, 18));

                por.setLayout(new BorderLayout());
                por.add(nomprodu, BorderLayout.CENTER);
                por.add(precprodu, BorderLayout.EAST);

                por.setSize(180,60);
                por.setVisible(true);

                    por.setLocation(1,tCombo);
                    pCombo.add(por);
                    tCombo = tCombo + 65;
                    pCombo.setPreferredSize(new Dimension(180,tCombo));

            }


            }catch(Exception ex){
                System.out.println("Error en cargar productos principal");
            }
        
        sCombo.setViewportView(pCombo);
        sCombo.getViewport().setView(pCombo);
        pCombo.setLayout(null);

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Deshabilita los campos
        txtNombre.setEditable(false);
        txtPrecio.setEditable(false);
        txtPrecioPedidosya.setEditable(false);
        
        //Deshabilita los botones Guardar y Cancelar
        btnNuevo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAgregar.setEnabled(false);
        
        txtIdProducto.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtPrecioPedidosya.setText("");
        
        
        tablap.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPrecioPedidosyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioPedidosyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioPedidosyaActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        product unidad = (product) cmbProductos.getSelectedItem();
        idunitario = unidad.getID();

    }//GEN-LAST:event_cmbProductosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Integer idcombo = Integer.parseInt(txtIdProducto.getText());
        conn.guardarcomboproducto(idcombo, Integer.parseInt(idunitario));
        v.visualizar_comboproducto(tProductos, idcombo);
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tProductos;
    private javax.swing.JTable tablap;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioPedidosya;
    // End of variables declaration//GEN-END:variables
}
