package Ordenes;

import java.sql.Date;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import Principales.FiltrosTextField;
import Principales.Ticket;
import Stock.TablaStock;

/**
 *
 * @author Franco
 */
public class FrameOrdenes extends javax.swing.JInternalFrame {
	Boolean nuevo = false;
	TablasOrdenes v = new TablasOrdenes();
	TablaStock vS = new TablaStock();
	String turno = "";
	Date fecha22 = new Date(System.currentTimeMillis());

	JTable tabla;
	ConexionOrdenes conn = new ConexionOrdenes();
	Boolean eligio = false;
	FiltrosTextField filtros = new FiltrosTextField();
	JTextField txtlocal;
	JTextField txtdelivery;
	JTextField txtefectivo;
	JTextField txtencalle;
	JTextField txtotros;
	JTable Stock;

	public FrameOrdenes(JTextField local, JTextField delivery, JTextField efectivo, JTextField encalle,
			JTextField otros, String turno1, JTable tStock) {
		initComponents();
		turno = turno1;
		Stock = tStock;
		txtlocal = local;
		txtdelivery = delivery;
		txtefectivo = efectivo;
		txtencalle = encalle;
		txtotros = otros;

		filtros.filtroeneteros(txtBuscar);
		filtros.filtrotamaño(txtBuscar, 10);

		v.visualizar_ordenes(tablap, "", 0);
		tablap.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			@Override
			public void valueChanged(ListSelectionEvent event) {
				// print first column value from selected row
				String orden = tablap.getValueAt(tablap.getSelectedRow(), 0).toString();
				String tipo = tablap.getValueAt(tablap.getSelectedRow(), 1).toString();
				String mpago = tablap.getValueAt(tablap.getSelectedRow(), 2).toString();
				String totales = tablap.getValueAt(tablap.getSelectedRow(), 3).toString();

				txtOrden.setText(orden);
				txtTipo.setText(tipo);
				txtMPago.setText(mpago);
				txtTotales.setText(totales);

				ResultSet rs = conn
						.select("ordenes WHERE tipo = '" + tipo + "' AND orden = " + Integer.parseInt(orden));

				try {
					while (rs.next()) {
						txtRecibo.setText(rs.getString(6));
					}
				} catch (Exception ex) {

				}
				btnEliminar.setEnabled(false);

			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		btnEliminar = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablap = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		txtTipo = new javax.swing.JTextField();
		txtMPago = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		txtOrden = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		cmbCategoria = new javax.swing.JComboBox<>();
		jLabel7 = new javax.swing.JLabel();
		btnBuscar = new javax.swing.JButton();
		txtBuscar = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtTotales = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtRecibo = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();

		setClosable(true);

		btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_edit-trash_9263.png"))); // NOI18N
		btnEliminar.setToolTipText("Eliminar");
		btnEliminar.setEnabled(false);
		btnEliminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEliminarActionPerformed(evt);
			}
		});

		tablap.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tablap);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGap(246, 246, 246).addComponent(btnEliminar)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(btnEliminar)
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		txtTipo.setEditable(false);
		txtTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		txtTipo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTipoActionPerformed(evt);
			}
		});

		txtMPago.setEditable(false);
		txtMPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		txtMPago.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtMPagoActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Tipo:");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("Orden:");

		txtOrden.setEditable(false);
		txtOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		txtOrden.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtOrdenActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Medio de pago:");

		jPanel3.setBackground(new java.awt.Color(153, 153, 153));

		cmbCategoria.setEditable(true);
		cmbCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Delivery" }));
		cmbCategoria.setFocusable(false);
		cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmbCategoriaActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel7.setText("Tipo:");

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_old-edit-find_23490.png"))); // NOI18N
		btnBuscar.setToolTipText("Buscar");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		txtBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		txtBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtBuscarActionPerformed(evt);
			}
		});

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel8.setText("Orden:");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel8)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtBuscar))
								.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel7).addGap(18, 18, 18)
										.addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnBuscar)
										.addGroup(jPanel3Layout.createSequentialGroup()
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(12, 12, 12)
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
																28, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(cmbCategoria,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(67, 67, 67)));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("Total:");

		txtTotales.setEditable(false);
		txtTotales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		txtTotales.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTotalesActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										jPanel2Layout.createSequentialGroup().addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(txtMPago))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout
														.createSequentialGroup().addComponent(jLabel2).addGap(4, 4, 4)
														.addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE,
																147, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel2Layout.createSequentialGroup().addGap(42, 42, 42)
														.addComponent(jLabel5)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(txtOrden, javax.swing.GroupLayout.PREFERRED_SIZE,
																57, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(15, 15, 15)))
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 126,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel5).addComponent(txtOrden,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(txtTotales,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(txtMPago,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		txtRecibo.setColumns(20);
		txtRecibo.setRows(5);
		jScrollPane2.setViewportView(txtRecibo);

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton1.setText("Imprimir");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(44, 44, 44)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(87, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jScrollPane2).addContainerGap()))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(66, 66, 66)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtOrdenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtOrdenActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtOrdenActionPerformed

	private void txtMPagoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMPagoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtMPagoActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		Integer orden = 0;
		if (!txtBuscar.getText().equals("")) {
			orden = Integer.parseInt(txtBuscar.getText());
		}
		Integer tipo = cmbCategoria.getSelectedIndex();
		v.visualizar_ordenesFiltro(tablap, tipo, orden);
		tablap.repaint();
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtBuscarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtBuscarActionPerformed

	private void txtTotalesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTotalesActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtTotalesActionPerformed

	private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTipoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtTipoActionPerformed

	private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbCategoriaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cmbCategoriaActionPerformed

	private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarActionPerformed

		int rta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar la orden?");
		if (rta != 0) {
			return;
		} else {
			Integer orden = Integer.parseInt(txtOrden.getText());
			String tipo = txtTipo.getText();

			conn.eliminarOrden(orden, tipo, turno);

			txtOrden.setText("");
			txtTipo.setText("");
			txtMPago.setText("");
			txtTotales.setText("");

			v.visualizar_ordenes(tablap, "", 0);
			tablap.setEnabled(true);

			btnEliminar.setEnabled(false);
			tablap.repaint();

		}
		conn.settotal(txtlocal, txtdelivery, txtefectivo, txtencalle, txtotros);
		vS.visualizar_stock(Stock);
	}// GEN-LAST:event_btnEliminarActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		String strin = txtRecibo.getText();
		Ticket.ImprimirDocumento(strin.getBytes());
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnEliminar;
	private javax.swing.JComboBox<String> cmbCategoria;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable tablap;
	private javax.swing.JTextField txtBuscar;
	private javax.swing.JTextField txtMPago;
	private javax.swing.JTextField txtOrden;
	private javax.swing.JTextArea txtRecibo;
	private javax.swing.JTextField txtTipo;
	private javax.swing.JTextField txtTotales;
	// End of variables declaration//GEN-END:variables
}
